# Generated by Django 4.0.4 on 2022-05-23 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='locations',
            name='location',
            field=models.CharField(max_length=1000),
        ),
    ]
