# Generated by Django 4.0.4 on 2022-05-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp1', '0003_remove_locations_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='id',
        ),
        migrations.AlterField(
            model_name='locations',
            name='location',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
